export interface ApartmentCommunalContractDto {
  amount1: number
  amount2: number
  amount3: number
  amount4: number
  amount5: number
  amount6: number
  amount7: number
  amount8: number
  amount9: number
  amount10: number
  amount11: number
  amount12: number
  paymentAmount1: number
  paymentAmount2: number
  paymentAmount3: number
  paymentAmount4: number
  paymentAmount5: number
  paymentAmount6: number
  paymentAmount7: number
  paymentAmount8: number
  paymentAmount9: number
  paymentAmount10: number
  paymentAmount11: number
  paymentAmount12: number
  status1: number
  status2: number
  status3: number
  status4: number
  status5: number
  status6: number
  status7: number
  status8: number
  status9: number
  status10: number
  status11: number
  status12: number
  binaBlockId: string
  binaBlockMertebeId: string
  binaBlockMertebeMenzilId: string
  binaBlockMertebeMenzilNomre: string
  binaBlockMertebeNomre: string
  binaBlockNomre: string
  binaId: string
  binaInfo: string
  customerFullName: string
  id: string
  il: number
  monthlyPayment: number
  roomCount: number
  sahe: number
  totalAmount: number
  totalPaymentAmount: number
  totalDept: number
}
